AisleOfPlans/Controllers/RequestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AisleOfPlans.Models;
using AisleOfPlans.View_Models;

namespace AisleOfPlans.Controllers
{
    public class RequestController : Controller
    {
        private LINQ2AIPASPBDDataContext context = new LINQ2AIPASPBDDataContext();

        // GET: Request
        public ActionResult Index( string status)
        {

            //Creating list to store list of catalogues
            IList<ServiceRequestViewModel> listOfRequests = new List<ServiceRequestViewModel>();

            IQueryable<ServiceRequest> query = null;
            IList<ServiceRequest> requests = new List<ServiceRequest>();

            //Creating query to retrieve all lists
            if (Session["ClientID"] != null)
            {
                query = context.ServiceRequests.Where(
                   r => r.CLIENT_ID == int.Parse(Session["ClientID"].ToString()) &&
                   r.REQUEST_STATUS.CompareTo(status) == 0);
                

                requests = query.ToList();
            }
            else
            {
                IList<Item> listOfItems = getListOfItems(int.Parse(Session["VendorID"].ToString()));
                ServiceRequest req;
                foreach (Item i in listOfItems)
                {
                    query = context.ServiceRequests.Where(
                                          request => request.ITEM_ID == i.ITEM_ID &&
                                          request.REQUEST_STATUS.CompareTo(status) == 0);
                    if(query.Count() == 0)
                    {
                        continue;
                    }
                    
                    foreach (ServiceRequest s in query)
                    {
                        req = new ServiceRequest
                        {
                            CLIENT_ID = s.CLIENT_ID,
                            ITEM_ID = s.ITEM_ID,
                            REQUEST_DATE = s.REQUEST_DATE,
                            REQUEST_DETAILS = s.REQUEST_DETAILS,
                            REQUEST_ID = s.REQUEST_ID,
                            REQUEST_STATUS = s.REQUEST_STATUS
                        };


                        requests.Add(req);
                    }
                }
            }

            foreach (var r in requests)
            {
                listOfRequests.Add(new ServiceRequestViewModel
                {
                    WeddingID = context.Weddings.Where(
                        w => w.CLIENT_ID == r.CLIENT_ID).Select(
                        w => w.WEDDING_ID).Single(),
                    Item_ID = r.ITEM_ID,
                    Request_ID = r.REQUEST_ID,
                    Date_Requested = r.REQUEST_DATE,
                    RequestDetails = r.REQUEST_DETAILS,
                    Status = r.REQUEST_STATUS,
                    //Extra stuff for display purposes
                    Image_URL = context.Items.Where(
                        i => i.ITEM_ID == r.ITEM_ID).Single().IMAGE_URL,
                    ItemName = context.Items.Where(
                        i => i.ITEM_ID == r.ITEM_ID).Single().ITEM_NAME
                });
            }

            return View(listOfRequests);
        }

        private IList<Item> getListOfItems(int vendorID)
        {
            IQueryable<Catalogue> listOfCatalogs = getItemCatalogue(vendorID);
            IQueryable<Item> query = null;
            IList<Item> listOfItems = new List<Item>();

            foreach (Catalogue c in listOfCatalogs)
            {
                query = from item in context.Items
                            where item.CATALOGUE_ID == c.CATALOGUE_ID
                            select item;
                foreach (Item i in query)
                {
                    listOfItems.Add(i);
                }
            }
           

            return listOfItems;
        }

        private IQueryable<Catalogue> getItemCatalogue(int vendorID)
        {
            var catalogue = context.Catalogues.Where(
                c => c.VENDOR_ID == vendorID);

            return catalogue;
        }

        private Vendor getItemVendor(Catalogue catalogue)
        {
            Vendor vendor = context.Vendors.Where(
                v => v.VENDOR_ID == catalogue.VENDOR_ID).Single<Vendor>();

            return vendor;
        }

        // GET: Request/Details/5
        public ActionResult Details(int id)
        {
            ServiceRequestViewModel model = context.ServiceRequests.Where(
            request => request.REQUEST_ID == id).Select(
            request => new ServiceRequestViewModel()
            {
                Item_ID = request.ITEM_ID,
                WeddingID = context.Weddings.Where(
                        w => w.CLIENT_ID == request.CLIENT_ID).Select(
                        w => w.WEDDING_ID).Single(),
               
                Date_Requested = request.REQUEST_DATE,
                RequestDetails = request.REQUEST_DETAILS,
                proofLocation = context.PaymentProofs.Where(
                        i => i.REQUEST_ID == request.REQUEST_ID).Select(
                        i => i.PROOF_URL).Single(),
                Status = request.REQUEST_STATUS,
                //Extra stuff for display purposes
                Image_URL = context.Items.Where(
                        i => i.ITEM_ID == request.ITEM_ID).Select(
                        i => i.IMAGE_URL).Single(),
                ItemName = context.Items.Where(
                        i => i.ITEM_ID == request.ITEM_ID).Select(
                        i => i.ITEM_NAME).Single(),
            }).SingleOrDefault();

            return View(model); 
        }

        // GET: Request/Create
        public ActionResult Create(int id)
        {
            ServiceRequestViewModel model = new ServiceRequestViewModel();
            model.Item_ID = id;
            model.ItemType = context.Items.Where(
                i => i.ITEM_ID == id).Single().ITEM_TYPE;

            return View(model);
        }

        // POST: Request/Create
        [HttpPost]
        public ActionResult Create(ServiceRequestViewModel model)
        {
            try
            {
                ServiceRequest request = new ServiceRequest
                {
                    CLIENT_ID = int.Parse(Session.Contents["ClientID"].ToString()),
                    REQUEST_DATE = System.DateTime.Now.ToLocalTime(),
                    REQUEST_STATUS = "Pending",
                    ITEM_ID = model.Item_ID
                };

                StoreDetails(request, model);

                context.ServiceRequests.InsertOnSubmit(request);
                context.SubmitChanges();

                return RedirectToAction("Index", new { status = request.REQUEST_STATUS });
            }
            catch
            {
                return View(model);
            }
        }

        private void StoreDetails(ServiceRequest request, ServiceRequestViewModel model)
        {
            if (model.ItemType.Contains("Attire"))
            {
                request.REQUEST_DETAILS = (model.NumItems + "," +
                    model.HeightMeasurement + ","+
                    model.BustMeasurement + "," +
                    model.WaistMeasurement + "," +
                    model.HipMeasurement + ","+
                    model.FashionDetails);
            }
            else if (model.ItemType.Contains("Shoes"))
            {
                request.REQUEST_DETAILS = (model.NumItems + "," +
                    model.FashionDetails );
            }
            else if(model.ItemType.Contains("Menu"))
            {
                request.REQUEST_DETAILS = (model.NumCateringDays + "," +
                    model.DieteryDetails );
            }
            else if(model.ItemType.Contains("Cake"))
            {
                request.REQUEST_DETAILS = (model.NumCakes + "," +
                    model.DieteryDetails);
            }
            else if(model.ItemType.Contains("Decorations"))
            {
                request.REQUEST_DETAILS = (model.NumPackages + "," +
                    model.ArtDetails);
            }
            else if(model.ItemType.Contains("Hair") || model.ItemType.Contains("Jewellery"))
            {
                request.REQUEST_DETAILS = (model.NumPeople + "," +
                    model.StylingDetails);
            }
            else if(model.ItemType.Contains("Transportation"))
            {
                request.REQUEST_DETAILS = (model.NumVehicles + "," +
                    model.NumVehicleDays + "," +
                    model.VehicleDetails );
            }
            else if(model.ItemType.Contains("Venue"))
            {
                request.REQUEST_DETAILS = (model.NumDays + "," +
                    model.isAccommodationRequired + "," +
                    model.VenueDetails);
            }
            else if(model.ItemType.Contains("Entertainment"))
            {
                request.REQUEST_DETAILS = (model.NumPerformanceHours + "," +
                    model.EntertainmentDetails);
            }
            else if(model.ItemType.Contains("Photographer") || model.ItemType.Contains("Videographer") || model.ItemType.Contains("Artist"))
            {
                request.REQUEST_DETAILS = (model.NumServiceHours + "," +
                    model.MediaDetails);
            }
        }

        public ActionResult Complete(int id)
        {
            ServiceRequestViewModel model = context.ServiceRequests.Where(
            request => request.REQUEST_ID == id).Select(
            request => new ServiceRequestViewModel()
            {
                Item_ID = request.ITEM_ID,
                WeddingID = context.Weddings.Where(
                        w => w.CLIENT_ID == request.CLIENT_ID).Select(
                        w => w.WEDDING_ID).Single(),
                Request_ID = request.REQUEST_ID,
                Status = request.REQUEST_STATUS,

AisleOfPlans/Views/Request/Accept.cshtml
@model AisleOfPlans.Models.ServiceRequestViewModel

<h3>Are you sure you want to Accept this?</h3>
<div>
    <h4>ServiceRequestViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Request_ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Request_ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Item_ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Item_ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Client_ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Client_ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ItemName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image_URL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image_URL)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Request_Details)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Request_Details)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date_Requested)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date_Requested)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Accept" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AisleOfPlans/Views/Request/Cancel.cshtml
@model AisleOfPlans.Models.ServiceRequestViewModel

<h3>Are you sure you want to cancel this?</h3>
<div>
    <h4>ServiceRequestViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Request_ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Request_ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Item_ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Item_ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Client_ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Client_ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ItemName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image_URL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image_URL)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Request_Details)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Request_Details)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date_Requested)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date_Requested)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Cancel" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AisleOfPlans/Views/Request/Complete.cshtml
@model AisleOfPlans.View_Models.ServiceRequestViewModel


<div>
    <h3>Please upload your Proof of Payment to complete</h3>

    <hr />

@using (Html.BeginForm(Html.BeginForm("Complete", "Request", FormMethod.Post, new { enctype = "multipart/form-data" })))
{
    @Html.HiddenFor(model => model.Item_ID)
@Html.HiddenFor(model => model.WeddingID)
    @Html.HiddenFor(model => model.Request_ID)
    @Html.HiddenFor(model => model.ItemName)
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ItemName)
        </dt>

        <dd>
            @Html.DisplayTextFor(model => model.ItemName)
        </dd>

        <dd>
            <img src=@Model.Image_URL alt=@Model.ItemName/>
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RequestDetails)
        </dt>

        <dd>
            @Html.DisplayTextFor(model => model.RequestDetails)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date_Requested)
        </dt>

        <dd>
            @Html.DisplayTextFor(model => model.Date_Requested)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayTextFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.proof)
        </dt>

        <dd >
            @Html.TextBoxFor(model => model.proof, htmlAttributes: new { @type = "file", @class = "form-control" })
            @Html.ValidationMessageFor(model => model.proof, "", new { @class = "text-danger" })
            <strong class="label-danger">@ViewBag.ErrorMessage</strong>
        </dd>

    </dl>
   
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Complete" class="btn btn-default" /> |
        </div>
    }
    @Html.ActionLink("Back to List", "Index", new { status = "Pending" })

</div>

AisleOfPlans/Views/Request/Decline.cshtml
@model AisleOfPlans.Models.ServiceRequestViewModel

<h3>Are you sure you want to decline this?</h3>
<div>
    <h4>ServiceRequestViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Request_ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Request_ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Item_ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Item_ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Client_ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Client_ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ItemName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image_URL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image_URL)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Request_Details)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Request_Details)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date_Requested)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date_Requested)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Decline" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AisleOfPlans/Views/Request/Details.cshtml
@model AisleOfPlans.View_Models.ServiceRequestViewModel

<div>
    <h4>Completed Request</h4>
    <hr />

    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ItemName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image_URL)
        </dt>

        <dd>
            <img class="img-thumbnail"width="100" height="100"  alt="@Model.ItemName" src="@Model.Image_URL"/>
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Request_Details)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Request_Details)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date_Requested)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date_Requested)
        </dd>

    </dl>

     @if(Model.Status.CompareTo("Complete")==0)
     {
         <a href="@Model.proofLocation">View Proof of Payment</a>
         <i>|</i>
     }
     @Html.ActionLink("Back to List", "Index", new {status = "Pending" })

</div>

AisleOfPlans/Views/Request/Index.cshtml
@model IEnumerable<AisleOfPlans.View_Models.ServiceRequestViewModel>

@{
    ViewBag.Title = "Index";

}

<h2>Requests</h2>

    @Html.ActionLink("Pending", "Index", "Request", routeValues: new { status = "Pending" }, 
    htmlAttributes: new { @class = "btn btn-primary" })

    @Html.ActionLink("Accepted", "Index", "Request", routeValues: new { status = "Accepted" }, 
    htmlAttributes: new { @class = "btn btn-primary" })

    @Html.ActionLink("Complete", "Index", "Request", routeValues: new { status = "Complete" },
    htmlAttributes: new { @class = "btn btn-primary" })

    @Html.ActionLink("Canceled", "Index", "Request", routeValues: new { status = "Canceled" },
    htmlAttributes: new { @class = "btn btn-primary" })

    @Html.ActionLink("Declined", "Index", "Request", routeValues: new { status = "Declined" },
    htmlAttributes: new { @class = " btn btn-primary" })


<table class="table" id="options">
    <tr>
        <th>
            <label> Item</label>
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date_Requested)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            <img class="img-thumbnail" width="100" height="100" src= "@item.Image_URL" alt=@item.ItemName/>
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Date_Requested)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Status)
        </td>
        <td>
           @Html.ActionLink("Details", "Details", new { id = item.Request_ID }, htmlAttributes: new { @class = "btn btn-primary" })
        @if (Session.Contents["VendorID"] != null && item.Status != "Declined" &&
                        item.Status != "Canceled" && item.Status != "Complete")//if statement for vendor
        {
            if(item.Status != "Accepted" && item.Status != "Complete")
            {
                @Ajax.ActionLink("Decline", "Decline", routeValues: new {id = item.Request_ID }, ajaxOptions: new AjaxOptions
               {
                   UpdateTargetId = "options",
                   HttpMethod = "POST",
                   InsertionMode = InsertionMode.Replace
               }, htmlAttributes: new { @class = "btn btn-primary" })

                @Ajax.ActionLink("Accept", "Accept", routeValues: new { id = item.Request_ID }, ajaxOptions: new AjaxOptions
             {
                 UpdateTargetId = "options",
                 HttpMethod = "POST",
                 InsertionMode = InsertionMode.Replace
             }, htmlAttributes: new { @class = "btn btn-primary" })
            }
        }

        @if (Session.Contents["ClientID"] != null && item.Status != "Declined" &&
                        item.Status != "Canceled" && item.Status != "Complete")//if statement for client
        {
            if (item.Status != "Complete")
            {
                @Ajax.ActionLink("Cancel", "Cancel", new {id = item.Request_ID },new AjaxOptions
                {
                    UpdateTargetId = "options",
                    HttpMethod = "POST",
                    InsertionMode = InsertionMode.Replace
                }, new { @class = "btn btn-primary" });

                if (item.Status != "Pending")
                {
                    @Html.ActionLink("Complete", "Complete", new { id = item.Request_ID }, htmlAttributes: new { @class = "btn btn-primary" })
                }
            }
            else
            {
                @Html.ActionLink("Update", "Update", new { id = item.Request_ID }, htmlAttributes: new { @class = "btn btn-primary" })
            }

        }
       
        </td>
    </tr>
}
</table>

<div>
    @Html.ActionLink("Back to Profile", "Index", "Profile", routeValues: null, htmlAttributes: new { @class = "btn btn-primary" })
</div>