AisleOfPlans/Controllers/VendorController.cs
using AisleOfPlans.Models;
using AisleOfPlans.View_Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AisleOfPlans.Controllers
{
    public class CatalogController : Controller
    {
        private LINQ2AIPASPBDDataContext context;

        private object loadListOfVendors(string objective)
        {
            IList<VendorViewModel> listOfVendors = new List<VendorViewModel>();

            var query = from vendor in context.Vendors
                        where vendor.TYPE.CompareTo(objective) == 0
                        select vendor;

            var vendors = query.ToList();

            foreach (var i in vendors)
            {
                listOfVendors.Add(new VendorViewModel
                {
                    Vendor_ID = i.VENDOR_ID,
                    Type = i.TYPE,
                    Logo_Location = i.LOGO_LOCATION,
                    Web_Address = i.WEB_ADDRESS,
                    Description = i.VENDOR_DESCRIPTION,
                    Business_Name = i.BUSINESS_NAME
                });
            }

            return listOfVendors;
        }

        private object loadListOfCatalogues(string objective)
        {
            IList<CatalogueViewModel> listOfCatalogues = new List<CatalogueViewModel>();

            var listOfVendors = from vendors in context.Vendors
                                where vendors.TYPE.CompareTo(objective) == 0
                                select vendors;

            IEnumerable<Catalogue> query = null;
            foreach (var v in listOfVendors)
            {
                query = from catalogue in context.Catalogues
                        where catalogue.VENDOR_ID == v.VENDOR_ID
                        select catalogue;
            }

            var catalogues = query.ToList();

            foreach (var c in catalogues)
            {
                listOfCatalogues.Add(new CatalogueViewModel
                {
                    ID = c.CATALOGUE_ID,
                    VendorID = c.VENDOR_ID,
                    Title = c.CAT_TITLE,
                    Description = c.CAT_DESCRIPTION
                });
            }

            return listOfCatalogues;
        }

        public CatalogController()
        {
            context = new LINQ2AIPASPBDDataContext();
        }

        // GET: list of catalogues
        public ActionResult Index()
        {
            int id = int.Parse(Session["VendorID"].ToString());
            //Creating list to store list of catalogues
            IList<CatalogueViewModel> listOfCatalogues = new List<CatalogueViewModel>();

            //Creating query to retrieve all lists
            var query = from catalogue in context.Catalogues
                        where catalogue.VENDOR_ID == id
                        select catalogue;

            var catalogues = query.ToList();

           foreach(var c in catalogues)
            {
                listOfCatalogues.Add(new CatalogueViewModel
                {
                    ID = c.CATALOGUE_ID,
                    VendorID = c.VENDOR_ID,
                    Title = c.CAT_TITLE,
                    Description = c.CAT_DESCRIPTION,
                    ImageUrl = c.CAT_BANNER
                });
            }

            return View(listOfCatalogues);
        }

        // GET: Catalogue/Create
        public ActionResult Create()
        {
            CatalogueViewModel model = new CatalogueViewModel();
            return View(model);
        }

        // POST: Catalogue/Create
        [HttpPost]
        public ActionResult Create(CatalogueViewModel model)
        {
            try
            {
                string savePath = null;
                string filePath = null;

                if(model.Image != null)
                {
                    if (model.Image.ContentType.Contains("jpeg") || model.Image.ContentType.Contains("jpg"))
                    {
                        savePath = Server.MapPath("~/Content/images/") + model.VendorID + model.Title + ".jpeg";
                        filePath = "../../Content/images/" + model.VendorID + model.Title + ".jpeg";
                        model.Image.SaveAs(savePath);
                    }
                    else if (model.Image.ContentType.Contains("png"))
                    {
                        savePath = Server.MapPath("~/Content/images/") + model.VendorID + model.Title + ".png";
                        filePath = "../../Content/images/" + model.VendorID + model.Title + ".png";
                        model.Image.SaveAs(savePath);
                    }
                    else if (model.Image.ContentType.Contains("bmp"))
                    {
                        savePath = Server.MapPath("~/Content/images/") + model.VendorID + model.Title + ".bmp";
                        filePath = "../../Content/images/" + model.VendorID + model.Title + ".bmp";
                        model.Image.SaveAs(savePath);
                    }
                    else if (model.Image.ContentType.Contains("gif"))
                    {
                        savePath = Server.MapPath("~/Content/images/") + model.VendorID + model.Title + ".gif";
                        filePath = "../../Content/images/" + model.VendorID + model.Title + ".gif";
                        model.Image.SaveAs(savePath);
                    }
                    else
                    {
                        filePath = "../../Content/images/defaultCatalogue.png";
                    }

                }
                else
                {
                    filePath = "../../Content/images/defaultCatalogue.png";
                }

                Catalogue cat = new Catalogue()
                {
                    CAT_TITLE = model.Title,
                    CAT_DESCRIPTION = model.Description,
                    CAT_BANNER = filePath,
                    VENDOR_ID = int.Parse(Session.Contents["VendorID"].ToString()),
                };
                context.Catalogues.InsertOnSubmit(cat);
                context.SubmitChanges();

               return RedirectToAction("Index");
            }
            catch
            {
                return View(model);
            }
        }

        // GET: Catalogue/Edit/5
        public ActionResult Edit(int id)
        {
            CatalogueViewModel model = context.Catalogues.Where(
                cat => cat.CATALOGUE_ID == id).Select(
                cat => new CatalogueViewModel()
                {
                    ID = cat.CATALOGUE_ID,
                    Title = cat.CAT_TITLE,
                    ImageUrl = cat.CAT_BANNER,
                    Description = cat.CAT_DESCRIPTION
                    
                }).SingleOrDefault();

            return View(model);
        }

        // POST: Catalogue/Edit/5
        [HttpPost]
        public ActionResult Edit(CatalogueViewModel model)
        {
            try
            {
                string savePath = null;
                string filePath = null;


                if (model.Image != null)
                {
                    if (model.Image.ContentType.Contains("jpeg") || model.Image.ContentType.Contains("jpg"))
                    {
                        savePath = Server.MapPath("~/Content/images/") + model.VendorID + model.Title + ".jpeg";
                        filePath = "../../Content/images/" + model.VendorID + model.Title + ".jpeg";
                        model.Image.SaveAs(savePath);
                    }
                    else if (model.Image.ContentType.Contains("png"))
                    {
                        savePath = Server.MapPath("~/Content/images/") + model.VendorID + model.Title + ".png";
                        filePath = "../../Content/images/" + model.VendorID + model.Title + ".png";
                        model.Image.SaveAs(savePath);
                    }
                    else if (model.Image.ContentType.Contains("bmp"))
                    {
                        savePath = Server.MapPath("~/Content/images/") + model.VendorID + model.Title + ".bmp";
                        filePath = "../../Content/images/" + model.VendorID + model.Title + ".bmp";
                        model.Image.SaveAs(savePath);
                    }
                    else if (model.Image.ContentType.Contains("gif"))
                    {
                        savePath = Server.MapPath("~/Content/images/") + model.VendorID + model.Title + ".gif";
                        filePath = "../../Content/images/" + model.VendorID + model.Title + ".gif";
                        model.Image.SaveAs(savePath);
                    }
                    else
                    {
                        filePath = "../../Content/images/defaultCatalogue.png";
                    }

                }
                else
                {
                    filePath = "../../Content/images/defaultCatalogue.png";
                }

                //Get catalogue matching current edit
                Catalogue cat = context.Catalogues.Where(
                    c => c.CATALOGUE_ID == model.ID).Single<Catalogue>();

                cat.CAT_TITLE = model.Title;
                cat.CAT_BANNER = filePath;
                cat.CAT_DESCRIPTION = model.Description;

                context.SubmitChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View(model);
            }
        }

        // GET: Catalogue/Delete/5
        public ActionResult Delete(int id)
        {
             CatalogueViewModel model = context.Catalogues.Where(
                cat => cat.CATALOGUE_ID == id).Select(
                cat => new CatalogueViewModel()
                {
                    ID = cat.CATALOGUE_ID,
                    Title = cat.CAT_TITLE,
                    Description = cat.CAT_DESCRIPTION

                }).SingleOrDefault();
            return View(model);

AisleOfPlans/Views/Catalog/Create.cshtml
@model AisleOfPlans.View_Models.CatalogueViewModel

@{
    ViewBag.Title = "Add Catalogue";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm("Create", "Catalog", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CatalogueViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
 
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Image, htmlAttributes: new { @type = "file", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Catalogs", "Index", routeValues: new { id = Model.ID })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AisleOfPlans/Views/Catalog/Delete.cshtml
@model AisleOfPlans.View_Models.CatalogueViewModel

@{
    ViewBag.Title = Model.Title;
}

<h2>Delete @ViewBag.Title </h2>

<h3>Are you sure you want to delete this Catalogue?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List of Catalogues", "Index")
        </div>
    }
</div>

AisleOfPlans/Views/Catalog/Edit.cshtml
@model AisleOfPlans.View_Models.CatalogueViewModel

@{
    ViewBag.Title = Model.Title;
}

<h2>Editing: @Model.Title</h2>


@using (Html.BeginForm("Edit", "Catalog", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Image, htmlAttributes: new { @type = "file", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Catalogs", "Index", routeValues: new { id = Session.Contents["VendorID"].ToString() }, htmlAttributes: new { @class = "btn btn-primary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AisleOfPlans/Views/Catalog/Index.cshtml
@model IEnumerable< AisleOfPlans.View_Models.CatalogueViewModel>

@{
    ViewBag.Title = "Catalogues";
}

<h2>Catalogues</h2>

<p>
    @Html.ActionLink("Create New", "Create", routeValues: null, htmlAttributes: new { @class = "btn btn-primary" })
</p>



@foreach (var cat in Model)
{
    <div class="row">
        <div class="col-lg-12" style="background-color:azure">
            <h2>@Html.DisplayFor(c => cat.Title)</h2>
            <div class="pull-right btn-group">
                <div class="btn "> @Html.ActionLink("Delete", "Delete", new { id = cat.ID }, htmlAttributes: new { @class = "btn btn-primary" })</div>
                <div class="btn ">@Html.ActionLink("Edit", "Edit", new { id = cat.ID }, htmlAttributes: new { @class = "btn btn-primary" })</div>
                <div class="btn ">@Html.ActionLink("View", "Index", "Item", routeValues: new { id = cat.ID }, htmlAttributes: new { @class = "btn btn-primary" })</div>
            </div>
        </div>
    </div>
    <hr />
}