AisleOfPlans/Controllers/ProfileController.cs
using AisleOfPlans.Models;
using AisleOfPlans.View_Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AisleOfPlans.Controllers
{
    public class ProfileController : Controller
    {
        private LINQ2AIPASPBDDataContext context = new LINQ2AIPASPBDDataContext();

        public ActionResult Index()
        {
            if((Session["ClientID"] != null))
                return RedirectToAction("LoadClientProfile");
            else if((Session["VendorID"] != null))
                return RedirectToAction("LoadVendorProfile");

            return RedirectToAction("Login", "Account");
        }

        // GET: Profile
        public ActionResult LoadClientProfile()
        {
            if(Session["UserID"]== null )
            {
                return RedirectToAction("Login", "Account");
            }
            else if(Session["ClientID"] == null)
            {
                return RedirectToAction("LoadVendorProfile");
            }

            ClientViewModel model = context.Clients.Where(
                  client => client.USER_ID == Session["UserID"].ToString()).Select(
                  client => new ClientViewModel()
                  {
                      User_ID = client.USER_ID,
                      Client_ID = client.CLIENT_ID,
                      Lastname = client.LASTNAME,
                      Partner1_Name = client.PARTNER_1_NAME,
                      Partner2_Name = client.PARTNER_2_NAME,
                      Pic_Location = client.PIC_LOCATION,
                      ClientWedding = context.Weddings.Where(
                          w => w.CLIENT_ID == client.CLIENT_ID).Single<Wedding>(),
                      
                  }).Single();

            var query = from plan in context.Plans
                        where plan.WEDDING_ID == model.ClientWedding.WEDDING_ID
                        select plan;

            //Setting up plans
            model.listOfPlans = new List<PlanViewModel>();

            foreach (Plan p in query)
            {
                model.listOfPlans.Add(new PlanViewModel
                {
                    Plan_ID = p.PLAN_ID,
                    Wedding_ID = p.WEDDING_ID,
                    Amount_Complete = p.AMOUNT_COMPLETE,
                    Deadline = p.DEADLINE,
                    PlanType_ID = p.PLAN_TYPE_ID,
                    Priority_level = p.PRIORITY_LEVEL,
                    Status = p.PLAN_STATUS,
                    Cost =(int) p.EST_COST,
                    Plan_Name = context.PlanTypes.Where(
                        type => type.PLAN_TYPE_ID == p.PLAN_TYPE_ID).Single().TYPE_NAME
                });
            }
            //Setting up budget
            model.budget = context.Budgets.Where(
                          b => b.WEDDING_ID == model.ClientWedding.WEDDING_ID).Single<Budget>();

            Session["ClientID"] = model.Client_ID;

            try
            { 
                Session["WeddingID"] = model.ClientWedding.WEDDING_ID;
            }
            catch 
            {
                return RedirectToAction("Create", "Wedding");
            }

     

            return View(model);
        }

        // GET: Profile
        public ActionResult LoadVendorProfile()
        {
            if (Session["UserID"] == null)
            {
                return RedirectToAction("Login", "Account");
            }
            else if (Session["VendorID"] == null)
            {
                return RedirectToAction("LoadClientProfile");
            }
            VendorViewModel model = context.Vendors.Where(
                              vendor => vendor.USER_ID == (
                              (Session["UserID"].ToString()))).Select(
                              vendor => new VendorViewModel()
                              {
                                  User_ID = vendor.USER_ID,
                                  Vendor_ID = vendor.VENDOR_ID,
                                  BankingDetails = vendor.BANKING_DETAILS,
                                  Business_Name = vendor.BUSINESS_NAME,
                                  Description = vendor.VENDOR_DESCRIPTION,
                                  Logo_Location = vendor.LOGO_LOCATION,
                                  Web_Address = vendor.WEB_ADDRESS,
                                  Type = vendor.TYPE,
                                  approxEarnings = new VendorReportViewModel(),
                                  
                              }).Single();

            var cats = context.Catalogues.Where(
                                      c => c.VENDOR_ID == model.Vendor_ID);

            ///////////////////////////*Calcualtions for most popular catalogue and item*/////////////////////////////////////////

            int highestForCat = 0;
            int currentCatTotal = 0;
            int highestForItem = 0;
            int currentItemTotal = 0;

            Catalogue mostPopCatalogue = null;
            Item mostPopItem = null;

            string[] requestDetails = null;

            model.NumCatalogues = cats.Count();

            if(cats.Count()>0)
            {
                foreach (Catalogue c in cats)
                {
                    var items = context.Items.Where(
                         i => i.CATALOGUE_ID == c.CATALOGUE_ID);

                    model.NumItems += items.Count();

                    if (items.Count() > 0)
                    {
                        currentCatTotal = 0;
                        foreach (Item i in items)
                        {
                            var itemsRequested = context.ServiceRequests.Where(
                                s => s.ITEM_ID == i.ITEM_ID && s.REQUEST_STATUS.CompareTo("Complete") == 0);

                            if (itemsRequested.Count() > 0)
                            {
                                currentItemTotal = 0;
                                foreach (ServiceRequest s in itemsRequested)
                                {
                                    requestDetails = s.REQUEST_DETAILS.Split(',');
                                    currentItemTotal += i.ITEM_PRICE * (int.Parse(requestDetails[0]));

                                    model.approxEarnings.TotalEstEarnings += currentItemTotal;

                                    if(highestForItem < currentItemTotal)
                                    {
                                        highestForItem = currentItemTotal;
                                        mostPopItem = i;
                                    }
                                }//end for requests
                                currentCatTotal += currentItemTotal;
                            }//end if
                        }//end for items

                        if (highestForCat < currentCatTotal)
                        {
                            highestForCat = currentCatTotal;
                            mostPopCatalogue = c;
                        }
                    }//end if

                }//end for catalogues
            }//end if

            model.approxEarnings.MostEarningCatalog = mostPopCatalogue;
            model.approxEarnings.HighestCatEarnings = highestForCat;
            model.approxEarnings.MostEarningItem = mostPopItem;
            model.approxEarnings.HighestItemEarnings = highestForItem;

            return View(model);
        }

        // GET: Profile/Create
        public ActionResult CreateClientProfile()
        {
            if (Session["UserID"] == null)
            {
                return RedirectToAction("Login", "Account");
            }

            ClientViewModel model = context.Clients.Where(
                 client => client.USER_ID == (Session["UserID"].ToString())).Select(
                 client => new ClientViewModel()
                 {
                     User_ID = client.USER_ID,
                     Client_ID = client.CLIENT_ID,
                     Lastname = client.LASTNAME,
                     Partner1_Name = client.PARTNER_1_NAME,
                     Partner2_Name = client.PARTNER_2_NAME,
                     Pic_Location = client.PIC_LOCATION,
                 }).Single();

            Session["ClientID"] = model.Client_ID;
            return View(model);
        }

        private void updateUser(string id)
        {
            try
            {
                AspNetUser user = context.AspNetUsers.Where(
                    u => u.Id == id).SingleOrDefault<AspNetUser>();

                user.IsSetup = "true";

                context.SubmitChanges();
            }
            catch (Exception e)
            {
                ViewBag.Error(e.StackTrace);
            }
        }

        // POST: Profile/Create
        [HttpPost]
        public ActionResult CreateClientProfile(ClientViewModel model)
        {
            try
            {
                string savePath = null;
                string filePath = null;


                if (model.Image != null)
                {
                    if (model.Image.ContentType.Contains("jpeg") || model.Image.ContentType.Contains("jpg"))
                    {
                        savePath = Server.MapPath("~/Content/images/") + model.Client_ID + model.Lastname + ".jpeg";
                        filePath = "../../Content/images/" + model.Client_ID + model.Lastname + ".jpeg";
                        model.Image.SaveAs(savePath);
                    }
                    else if (model.Image.ContentType.Contains("png"))
                    {
                        savePath = Server.MapPath("~/Content/images/") + model.Client_ID + model.Lastname + ".png";
                        filePath = "../../Content/images/" + model.Client_ID + model.Lastname + ".png";
                        model.Image.SaveAs(savePath);
                    }
                    else if (model.Image.ContentType.Contains("bmp"))
                    {

AisleOfPlans/Views/Wedding/Create.cshtml
@model AisleOfPlans.View_Models.WeddingViewModel

@{
    IList<SelectListItem> listOfThemes = new List<SelectListItem>();

    SelectListItem modernItem = new SelectListItem();
    modernItem.Text = "Modern";
    listOfThemes.Add(modernItem);

    SelectListItem traditionalItem = new SelectListItem();
    modernItem.Text = "Traditional";
    listOfThemes.Add(traditionalItem);

    SelectListItem futuristicItem = new SelectListItem();
    modernItem.Text = "Futuristic";
    listOfThemes.Add(futuristicItem);

    SelectListItem minimalistItem = new SelectListItem();
    modernItem.Text = "Minimalist";
    listOfThemes.Add(minimalistItem);

    SelectListItem customItem = new SelectListItem();
    modernItem.Text = "Multi-themed";
    listOfThemes.Add(customItem);

    SelectListItem avangardItem = new SelectListItem();
    modernItem.Text = "Avant Garde";
    listOfThemes.Add(avangardItem);

    SelectListItem artistic = new SelectListItem();
    modernItem.Text = "Artistic";
    listOfThemes.Add(avangardItem);

}

<h2>Please tell us about your plan</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>WeddingViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.WeddingDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WeddingDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WeddingDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Theme, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Theme,listOfThemes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Theme, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.budget.Budget_Available, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.budget.Budget_Available, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.budget.Budget_Available, "", new { @class = "text-danger" })
            </div>
        </div>

        <h4>Optional</h4>

        <div class="form-group">
            @Html.LabelFor(model => model.Street, htmlAttributes: new { @class = "control-label col-md-2" })

            <div class="col-md-10">
                @Html.EditorFor(model => model.Street, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Street, "", new { @class = "text-danger" })
            </div>

            @Html.LabelFor(model => model.Suburb, htmlAttributes: new { @class = "control-label col-md-2" })

            <div class="col-md-10">
                @Html.EditorFor(model => model.Suburb, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Street, "", new { @class = "text-danger" })
            </div>

            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })

            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>

            @Html.LabelFor(model => model.Province, htmlAttributes: new { @class = "control-label col-md-2" })

            <div class="col-md-10">
                @Html.EditorFor(model => model.Province, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Street, "", new { @class = "text-danger" })
            </div>

            @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })

            <div class="col-md-10">
                @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AisleOfPlans/Views/Wedding/Edit.cshtml
@model AisleOfPlans.View_Models.WeddingViewModel

@{
    IList<SelectListItem> listOfThemes = new List<SelectListItem>();

    SelectListItem modernItem = new SelectListItem();
    modernItem.Text = "Modern";
    listOfThemes.Add(modernItem);

    SelectListItem traditionalItem = new SelectListItem();
    traditionalItem.Text = "Traditional";
    listOfThemes.Add(traditionalItem);

    SelectListItem futuristicItem = new SelectListItem();
    futuristicItem.Text = "Futuristic";
    listOfThemes.Add(futuristicItem);

    SelectListItem minimalistItem = new SelectListItem();
    minimalistItem.Text = "Minimalist";
    listOfThemes.Add(minimalistItem);

    SelectListItem customItem = new SelectListItem();
    customItem.Text = "Multi-themed";
    listOfThemes.Add(customItem);

    SelectListItem avangardItem = new SelectListItem();
    avangardItem.Text = "Avant Garde";
    listOfThemes.Add(avangardItem);

    SelectListItem artistic = new SelectListItem();
    artistic.Text = "Artistic";
    listOfThemes.Add(artistic);

}

<h2>Edit Wedding Details</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Wedding_ID)
        @Html.HiddenFor(model => model.budget.Budget_ID)

        <div class="form-group">
            @Html.LabelFor(model => model.WeddingDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.WeddingDate, new { htmlAttributes = new { @class = "form-control datepicker" } })
                @Html.ValidationMessageFor(model => model.WeddingDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Theme, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Theme, listOfThemes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Theme, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.budget.Budget_Available, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.budget.Budget_Available, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.budget.Budget_Available, "", new { @class = "text-danger" })
            </div>
        </div>

        <h4>Optional</h4>

        <div class="form-group">
            @Html.LabelFor(model => model.Street, htmlAttributes: new { @class = "control-label col-md-2" })

            <div class="col-md-10">
                @Html.EditorFor(model => model.Street, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Street, "", new { @class = "text-danger" })
            </div>

            @Html.LabelFor(model => model.Suburb, htmlAttributes: new { @class = "control-label col-md-2" })

            <div class="col-md-10">
                @Html.EditorFor(model => model.Suburb, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Street, "", new { @class = "text-danger" })
            </div>

            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })

            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>

            @Html.LabelFor(model => model.Province, htmlAttributes: new { @class = "control-label col-md-2" })

            <div class="col-md-10">
                @Html.EditorFor(model => model.Province, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Street, "", new { @class = "text-danger" })
            </div>

            @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })

            <div class="col-md-10">
                @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Wedding", "Index", routeValues: null, htmlAttributes: new { @class = "btn btn-primary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript">
        $(document).ready(function(){
            $('.datetimepicker').datepicker();

            });
    </script>
}

AisleOfPlans/Views/Wedding/Index.cshtml
@model AisleOfPlans.View_Models.WeddingViewModel

@{
   
}

<h2>View Wedding Details</h2>

<div>
    <h4>Celebrating the union of @Model.Client.Partner1_Name and @Model.Client.Partner2_Name</h4>
    <img src="@Model.Client.Pic_Location" alt="Mr and Mrs @Model.Client.Lastname's Picture"/>
    <hr />

    <dl class="dl-horizontal">
        <dt>
            @Html.HiddenFor(model => model.Client_ID)
        </dt>

        <dd>
            @Html.HiddenFor(model => model.Wedding_ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WeddingDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WeddingDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Theme)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Theme)
        </dd>

    </dl>

    <!--//////////////////////////////Google Map of Location of Wedding/////////////////////////////////////////////////////////-->

</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { WeddingID = Model.Wedding_ID}) |
    @Html.ActionLink("Back to Profile", "Index","Profile")
</p>